# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyF' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.5'
  pod 'RxSwift',    '~> 4.0.0'
  pod 'RxCocoa',    '~> 4.0.0'
  pod 'Alamofire'
  pod 'CocoaLumberjack/Swift'
  # Pods for MyF

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
end
